// Sample users data for database initialization
module.exports = [
  {
    username: 'SungJinWoo',
    email: 'jinwoo@hunter.com',
    password: 'password123', // Will be hashed by the model hooks
    rank: 'S',
    level: 100,
    experience: 10000,
    gold: 9999999,
    health: 10000,
    mana: 5000,
    strength: 1000,
    intelligence: 800,
    agility: 900,
    hunts: 500,
    kills: 2000,
    dungeons: 100,
    bossKills: 50,
    soloHunts: 300,
    skillPoints: 100,
    avatar: 'jinwoo-avatar.png',
    isAdmin: true
  },
  {
    username: 'HunterE',
    email: 'hunter_e@hunter.com',
    password: 'hunter123',
    rank: 'E',
    level: 5,
    experience: 200,
    gold: 1500,
    health: 120,
    mana: 60,
    strength: 15,
    intelligence: 12,
    agility: 14,
    hunts: 10,
    kills: 25,
    dungeons: 2,
    bossKills: 0,
    soloHunts: 5,
    skillPoints: 3,
    avatar: 'default-avatar.png',
    isAdmin: false
  },
  {
    username: 'HunterD',
    email: 'hunter_d@hunter.com',
    password: 'hunter123',
    rank: 'D',
    level: 15,
    experience: 1200,
    gold: 5000,
    health: 200,
    mana: 100,
    strength: 25,
    intelligence: 22,
    agility: 24,
    hunts: 30,
    kills: 100,
    dungeons: 5,
    bossKills: 1,
    soloHunts: 15,
    skillPoints: 8,
    avatar: 'default-avatar.png',
    isAdmin: false
  },
  {
    username: 'HunterC',
    email: 'hunter_c@hunter.com',
    password: 'hunter123',
    rank: 'C',
    level: 30,
    experience: 5000,
    gold: 15000,
    health: 350,
    mana: 200,
    strength: 45,
    intelligence: 40,
    agility: 42,
    hunts: 80,
    kills: 300,
    dungeons: 15,
    bossKills: 5,
    soloHunts: 40,
    skillPoints: 15,
    avatar: 'default-avatar.png',
    isAdmin: false
  },
  {
    username: 'HunterB',
    email: 'hunter_b@hunter.com',
    password: 'hunter123',
    rank: 'B',
    level: 50,
    experience: 15000,
    gold: 50000,
    health: 600,
    mana: 400,
    strength: 80,
    intelligence: 75,
    agility: 78,
    hunts: 150,
    kills: 700,
    dungeons: 30,
    bossKills: 12,
    soloHunts: 80,
    skillPoints: 25,
    avatar: 'default-avatar.png',
    isAdmin: false
  },
  {
    username: 'HunterA',
    email: 'hunter_a@hunter.com',
    password: 'hunter123',
    rank: 'A',
    level: 75,
    experience: 50000,
    gold: 200000,
    health: 1200,
    mana: 800,
    strength: 150,
    intelligence: 140,
    agility: 145,
    hunts: 300,
    kills: 1500,
    dungeons: 60,
    bossKills: 25,
    soloHunts: 150,
    skillPoints: 50,
    avatar: 'default-avatar.png',
    isAdmin: false
  }
];
